//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.10 at 11:46:37 PM IST 
//


package com.irctc.req.bindings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BookTicketType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BookTicketType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PassengerInfo" type="{}PassengerInfoType"/>
 *         &lt;element name="JourneyInfo" type="{}JourneyInfoType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BookTicketType", propOrder = {
    "passengerInfo",
    "journeyInfo"
})
public class BookTicketType {

    @XmlElement(name = "PassengerInfo", required = true)
    protected PassengerInfoType passengerInfo;
    @XmlElement(name = "JourneyInfo", required = true)
    protected JourneyInfoType journeyInfo;

    /**
     * Gets the value of the passengerInfo property.
     * 
     * @return
     *     possible object is
     *     {@link PassengerInfoType }
     *     
     */
    public PassengerInfoType getPassengerInfo() {
        return passengerInfo;
    }

    /**
     * Sets the value of the passengerInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PassengerInfoType }
     *     
     */
    public void setPassengerInfo(PassengerInfoType value) {
        this.passengerInfo = value;
    }

    /**
     * Gets the value of the journeyInfo property.
     * 
     * @return
     *     possible object is
     *     {@link JourneyInfoType }
     *     
     */
    public JourneyInfoType getJourneyInfo() {
        return journeyInfo;
    }

    /**
     * Sets the value of the journeyInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link JourneyInfoType }
     *     
     */
    public void setJourneyInfo(JourneyInfoType value) {
        this.journeyInfo = value;
    }

}
