//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.10 at 11:46:37 PM IST 
//


package com.irctc.req.bindings;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.irctc.req.bindings package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _BookTicket_QNAME = new QName("", "BookTicket");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.irctc.req.bindings
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BookTicketType }
     * 
     */
    public BookTicketType createBookTicketType() {
        return new BookTicketType();
    }

    /**
     * Create an instance of {@link PassengerInfoType }
     * 
     */
    public PassengerInfoType createPassengerInfoType() {
        return new PassengerInfoType();
    }

    /**
     * Create an instance of {@link JourneyInfoType }
     * 
     */
    public JourneyInfoType createJourneyInfoType() {
        return new JourneyInfoType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BookTicketType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BookTicket")
    public JAXBElement<BookTicketType> createBookTicket(BookTicketType value) {
        return new JAXBElement<BookTicketType>(_BookTicket_QNAME, BookTicketType.class, null, value);
    }

}
